name: openwrt_core

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    name: openwrt_core - [${{ matrix.target }}]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          - x86_64
          - aarch64_generic
          
    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        ref: ${{ matrix.target }}

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        echo "target=x86_64-6.6" >> "$GITHUB_ENV"

    - name: Sync kernel modules
      run: |
        if [ "${{ matrix.target }}" = "x86_64" ]; then
          manifest_url="https://github.com/zhiern/OpenWRT/releases/download/X86_64/openwrt-x86-64-generic.manifest"
          kernel_url="https://github.com/zhiern/OpenWRT/releases/download/X86_64/kernel.tar.gz"
        elif [ "${{ matrix.target }}" = "aarch64_generic" ]; then
          manifest_url="https://github.com/zhiern/OpenWRT/releases/download/Rockchip/openwrt-rockchip-armv8.manifest"
          kernel_url="https://github.com/zhiern/OpenWRT/releases/download/Rockchip/kernel.tar.gz"
        fi

        # 下载 manifest 并提取 kernel 版本
        curl -L "$manifest_url" -o manifest.txt --progress-bar
        kernel_ver=$(grep -E "^kernel -" manifest.txt | awk '{print $3}')
        echo "RELEASE_NAME=$kernel_ver" >> "$GITHUB_ENV"
        echo "Extracting kernel to folder: $kernel_ver"

        # 创建以版本号命名的目录并解压
        mkdir -p "$kernel_ver"
        curl -L "$kernel_url" -o kernel.tar.gz --progress-bar
        tar -zxf kernel.tar.gz --strip-components=1 -C "$kernel_ver"

        # 清理
        rm -f kernel.tar.gz manifest.txt

    - name: Git push
      continue-on-error: true
      run: |
        git config --global user.email "zhiern@users.noreply.github.com"
        git config --global user.name "actions-user"
        [ -d .git ] && git init
        git add --all
        git commit -sm "${{ env.RELEASE_NAME }}"
        git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${{ matrix.target }}
