name: openwrt_core

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    name: openwrt_core - [${{ matrix.target }}]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
#          - aarch64_generic
          - x86_64

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        ref: ${{ matrix.target }}

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        if [ "${{ matrix.target }}" = "aarch64_generic" ]; then
          echo "target=aarch64-6.6" >> "$GITHUB_ENV"
        elif [ "${{ matrix.target }}" = "x86_64" ]; then
          echo "target=x86_64-6.6" >> "$GITHUB_ENV"
        fi

    - name: Sync kernel modules
      run: |
        kmod="https://github.com/zhiern/ZeroWrt/releases/download/OpenWrt-v24.10.2/x86_64-kmodpkg.tar.gz"
        kmod_name=$(basename $kmod | sed 's/\.tar\.gz$//;s/^[^-]*-//')
        rm -rf $kmod_name
        curl -L $kmod -o $kmod_name.tar.gz --progress-bar
        tar zxf $kmod_name.tar.gz && rm -f $kmod_name.tar.gz
        echo "RELEASE_NAME=$kmod_name" >> "$GITHUB_ENV"
        echo $kmod_name
        
    - name: Git push
      continue-on-error: true
      run: |
        git config --local user.name "gitea-action"
        git config --local user.email "git@kejizero.online"
        [ -d .git ] && git init
        git add --all
        git commit -sm "${{ env.RELEASE_NAME }}"
        git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${{ matrix.target }}
