name: openwrt_core

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    name: openwrt_core - [${{ matrix.target }}]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          - aarch64_generic
          - x86_64

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        ref: ${{ matrix.target }}

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        if [ "${{ matrix.target }}" = "aarch64_generic" ]; then
          echo "target=aarch64-6.6" >> "$GITHUB_ENV"
        elif [ "${{ matrix.target }}" = "x86_64" ]; then
          echo "target=x86_64-6.6" >> "$GITHUB_ENV"
        fi

    - name: Sync kernel modules
      run: |
        wget https://github.com/zhiern/ZeroWrt/releases/download/OpenWrt-v24.10.2/${{ matrix.target }}-kmodpkg.tar.gz -O - | tar -xz
        cd kmodpkg
        new_name=$(basename packages/kernel_*.ipk | sed -E 's/^kernel_//; s/\.ipk$//; s/_x86_64$//; s/_aarch64_generic$//')
        mv packages "$new_name"
        for f in *; do
          [ "$f" != "$new_name" ] && mv "$f" "$new_name"/
        done
        echo "kmod_dir=kmodpkg/$new_name" >> "$GITHUB_ENV"

    - name: Release Kernel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        username: ftpopenwrt
        server: ${{ secrets.ftp_address }}
        password: ${{ secrets.ftp_password }}
        server-dir: core/${{ matrix.target }}/
        local-dir: kmodpkg/
        dangerous-clean-slate: false
