name: openwrt_core

on:
  workflow_dispatch:
  repository_dispatch:
    types: [sync]

permissions:
  contents: write

jobs:
  build:
    name: openwrt_core - [${{ matrix.target }}]
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        target:
          - x86_64

    steps:
    - name: Checkout
      continue-on-error: true
      uses: actions/checkout@main
      with:
        ref: ${{ matrix.target }}

    - name: Setup variables
      run: |
        sudo timedatectl set-timezone 'Asia/Shanghai'
        echo "target=x86_64-6.6" >> "$GITHUB_ENV"

    - name: Sync kernel modules
      run: |
        # 下载文件
        curl -L https://github.com/zhiern/OpenWRT/releases/download/X86_64/openwrt-x86-64-generic.manifest -o manifest.txt --progress-bar
        kernel_ver=$(grep -E "^kernel -" manifest.txt | awk '{print $3}')
        echo "RELEASE_NAME=$kernel_ver" >> "$GITHUB_ENV"

        # 创建干净的工作目录
        mkdir -p "$kernel_ver"

        # 下载并解压到该目录中（关键）
        curl -L https://github.com/zhiern/OpenWRT/releases/download/X86_64/kernel.tar.gz -o kernel.tar.gz --progress-bar
        tar -zxf kernel.tar.gz -C "$kernel_ver"
        rm -f kernel.tar.gz manifest.txt
        

    - name: Git push
      continue-on-error: true
      run: |
        git config --global user.email "zhiern@users.noreply.github.com"
        git config --global user.name "actions-user"
        [ -d .git ] && git init
        git add --all
        git commit -sm "${{ env.RELEASE_NAME }}"
        git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}" HEAD:${{ matrix.target }}
