name: Upload Extracted Kernel Files to FTP (Rockchip)

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 创建工作目录
        run: mkdir -p kernel

      - name: 下载 kernel.tar.gz
        run: |
          wget -O kernel/kernel.tar.gz https://github.com/zhiern/ZeroWrt-Action/releases/download/Rockchip/kernel.tar.gz

      - name: 下载 manifest 文件并提取 kernel hash
        run: |
          wget -O kernel/openwrt-rockchip-armv8.manifest https://github.com/zhiern/ZeroWrt-Action/releases/download/Rockchip/openwrt-rockchip-armv8.manifest
          HASH=$(grep '^kernel' kernel/openwrt-rockchip-armv8.manifest | awk '{print $3}')
          echo "KERNEL_HASH=$HASH" >> $GITHUB_ENV

      - name: 解压 kernel.tar.gz 到对应 hash 目录并删除压缩包
        run: |
          mkdir -p kernel/${{ env.KERNEL_HASH }}
          tar -xzf kernel/kernel.tar.gz -C kernel/${{ env.KERNEL_HASH }}
          rm kernel/kernel.tar.gz

      - name: 上传解压后的内核文件到 FTP（hash 目录）
        uses: sbwml/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.ftp_address }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: core/aarch64_generic/${{ env.KERNEL_HASH }}/
          local-dir: kernel/${{ env.KERNEL_HASH }}/

