name: Upload Extracted Kernel Files to FTP (X86_64)

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: 创建工作目录
        run: mkdir -p kernel

      - name: 下载 kernel.tar.gz
        run: |
          wget -O kernel/kernel.tar.gz https://github.com/zhiern/ZeroWrt-Action/releases/download/X86_64/kernel.tar.gz

      - name: 下载 manifest 文件并提取 kernel hash
        run: |
          wget -O kernel/openwrt-x86-64-generic.manifest https://github.com/zhiern/ZeroWrt-Action/releases/download/X86_64/openwrt-x86-64-generic.manifest
          HASH=$(grep '^kernel' kernel/openwrt-x86-64-generic.manifest | awk '{print $3}')
          echo "KERNEL_HASH=$HASH" >> $GITHUB_ENV

      - name: 解压 kernel.tar.gz 到 kernel/${{ env.KERNEL_HASH }} 并删除压缩包
        run: |
          mkdir -p kernel/${{ env.KERNEL_HASH }}
          tar -xzf kernel/kernel.tar.gz -C kernel
          mv kernel/kernel/* kernel/${{ env.KERNEL_HASH }}/
          rm -rf kernel/kernel kernel/kernel.tar.gz kernel/openwrt-x86-64-generic.manifest
          
      - name: 上传解压后的内核文件到 FTP
        uses: sbwml/FTP-Deploy-Action@master
        with:
          server: ${{ secrets.ftp_address }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          server-dir: core/x86_64/
          local-dir: kernel/
